CREATE TABLE Products(
    products_id int GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    name varchar(10),    
    PRIMARY KEY (products_id)    
);

CREATE TABLE Orders(
    orders_id int GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    order_date date,
    name varchar(10),    
    PRIMARY KEY (orders_id)
);

CREATE TABLE Order_Items(
    order_items_id int GENERATED BY DEFAULT AS IDENTITY 
                                         (START WITH 1, INCREMENT BY 1) NOT NULL,
    amount int,
    order_id int REFERENCES Orders(orders_id),
    product_id int,
    PRIMARY KEY (order_items_id)
);